SchedulerJobs/SchedulerJobs.Common/ApiHelper/ApiUriFactory.cs, SchedulerJobs/SchedulerJobs.Services/CloseConferenceService.cs, SchedulerJobs/SchedulerJobs.Services/VideoApi/Contracts/ConferenceSummaryResponse.cs, SchedulerJobs/SchedulerJobs.Services/VideoApiService.cs, SchedulerJobs/SchedulerJobs.Services/VideoApiServiceFake.cs, SchedulerJobs/SchedulerJobs.UnitTests/CloseConferenceServiceTest.cs, SchedulerJobs/SchedulerJobs/Service/ConfigLoader.cs
https://tools.hmcts.net/jira/browse/VIH-5399
Added call to api to remove virtual courtrooms for closed hearings
```
[X ] Yes
[ ] No
```
=> Added remove virtual court room

SchedulerJobs/SchedulerJobs/Service/ConfigLoader.cs
VIH-5399
App configuration modification
```
[X ] Yes
[ ] No
```
=> set filter for app config labels

azure-pipelines.yml
n/a
Added trigger for release branch
```
[ ] Yes
[x ] No
```
=> Added trigger for release branch

SchedulerJobs/SchedulerJobs.Common/ApiHelper/ApiUriFactory.cs, SchedulerJobs/SchedulerJobs.Services/CloseConferenceService.cs, SchedulerJobs/SchedulerJobs.Services/VideoApi/Contracts/ExpiredConferencesResponse.cs, SchedulerJobs/SchedulerJobs.Services/VideoApiService.cs, SchedulerJobs/SchedulerJobs.UnitTests/Functions/DeleteAudiorecordingApplicationsFunction/RunDeleteAudiorecordingApplicationsFunctionTest.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/CloseConferenceServiceTest.cs, SchedulerJobs/SchedulerJobs/Functions/DeleteAudiorecordingApplicationsFunction.cs
https://tools.hmcts.net/jira/browse/VIH-6195
Added function to delete audio apps
```
[ X] Yes
[ ] No
```
=> VIH-6195 added function to delete audio apps

SchedulerJobs/SchedulerJobs.Services/CloseConferenceService.cs
https://tools.hmcts.net/jira/browse/VIH-6195
Fix code smell, removed unused variable
```
[X ] Yes
[ ] No
```
=> VIH-6195 removed unused variable

SchedulerJobs/SchedulerJobs.Services/VideoApiService.cs
https://tools.hmcts.net/jira/browse/VIH-6195
Fix -verb Delete 
```
[ X] Yes
[ ] No
```
=> VIH-6195 change verb to Delete

SchedulerJobs/SchedulerJobs.Common/ApiHelper/ApiUriFactory.cs, SchedulerJobs/SchedulerJobs.Common/ApiHelper/BookingsServiceTokenHandler.cs, SchedulerJobs/SchedulerJobs.Common/ApiHelper/UserServiceTokenHandler.cs, SchedulerJobs/SchedulerJobs.Common/Configuration/HearingServicesConfiguration.cs, SchedulerJobs/SchedulerJobs.Services/AnonymiseHearingsConferencesDataService.cs, SchedulerJobs/SchedulerJobs.Services/BookingApi/Contracts/UserWithClosedConferencesResponse.cs, SchedulerJobs/SchedulerJobs.Services/BookingsApiService.cs, SchedulerJobs/SchedulerJobs.Services/UserApiService.cs, SchedulerJobs/SchedulerJobs.Services/VideoApiService.cs, SchedulerJobs/SchedulerJobs.UnitTests/Common/ApiHelper/BookingServiceTokenhandlerTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Common/ApiHelper/UserServiceTokenHandlerTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Functions/AnonymiseHearingsConferencesAndDeleteAadUsersFunction/RunAnonymiseHearingsConferencesAndDeleteAadUsersFunctionTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/AnonymiseHearingsConferencesDataServiceTests.cs, SchedulerJobs/SchedulerJobs.sln, SchedulerJobs/SchedulerJobs/Functions/AnonymiseHearingsConferencesAndDeleteAadUsersFunction.cs, SchedulerJobs/SchedulerJobs/Properties/serviceDependencies.json, SchedulerJobs/SchedulerJobs/Properties/serviceDependencies.local.json, SchedulerJobs/SchedulerJobs/Service/ConfigLoader.cs, SchedulerJobs/SchedulerJobs/Service/TraceCategory.cs, SchedulerJobs/SchedulerJobs/Startup.cs, SchedulerJobs/run_coverage.bat, SchedulerJobs/run_coverage.sh
https://tools.hmcts.net/jira/browse/VIH-1962
- added a new function to anonymise hearing and conference data and delete aad user with hearings older than 3 months and no hearings in the future.
```
[ ] Yes
[x] No
```
=> VIH-1962 create automatic process to anonymise data and delete user accounts in line with gdpr

SchedulerJobs/SchedulerJobs.Common/ApiHelper/ApiUriFactory.cs, SchedulerJobs/SchedulerJobs.Services/RemoveHeartbeatsForConferencesService.cs, SchedulerJobs/SchedulerJobs.Services/VideoApiService.cs, SchedulerJobs/SchedulerJobs.UnitTests/Functions/RemoveHeartbeatsForConferencesFunction/RemoveHeartbeatsForConferencesFunctionTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/RemoveHeartbeatsForConferencesServiceTests.cs, SchedulerJobs/SchedulerJobs/Functions/RemoveHeartbeatsForConferencesFunction.cs, SchedulerJobs/SchedulerJobs/Startup.cs
https://tools.hmcts.net/jira/browse/VIH-6097
- added new function to clear heartbeats
```
[ ] Yes
[x] No
```
=> VIH-6097 Clear_down_hearing_heartbeat_data_after_2_weeks

SchedulerJobs/SchedulerJobs.Services/UserApiService.cs
https://tools.hmcts.net/jira/browse/VIH-6403
- remove check for response for the delete call.
```
[ ] Yes
[x] No
```
=> VIH-6403 Update gdpr job to exclude the test accounts

CODEOWNERS, azure-pipelines.yml
VIH-6594 
update pipeline
```
[ ] Yes
[ ] No
```
=> VIH-6594 update pipeline

SchedulerJobs/SchedulerJobs/Functions/ClearHearingsFunction.cs, SchedulerJobs/SchedulerJobs/Functions/DeleteAudiorecordingApplicationsFunction.cs
https://tools.hmcts.net/jira/browse/VIH-6994
Change time for wowza related functions
```
[X ] Yes
[ ] No
```
=> VIH-6994 change time for Wowza related functions

azure-pipelines.release.yml
VIH-7409
update release pipeline
```
[ ] Yes
[x] No
```
=> VIH-7409 update release pipeline

azure-pipelines.release.yml
VIH-7409
disable ac tests
```
[ ] Yes
[ ] No
```
=> VIH-7409 disable ac tests on deploy

SchedulerJobs/SchedulerJobs/Dockerfile
VIH-7409
sds docker file changes
```
[ ] Yes
[x] No
```
=> VIH-7409 sds docker file changes

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/ApiHelper/ApiRequestHelper.cs, SchedulerJobs/SchedulerJobs.Common/ApiHelper/ELinksApiDelegatingHandler.cs, SchedulerJobs/SchedulerJobs.Common/Configuration/ServicesConfiguration.cs, SchedulerJobs/SchedulerJobs.Common/Exceptions/ELinksApiException.cs, SchedulerJobs/SchedulerJobs.Common/Models/JudiciaryPersonModel.cs, SchedulerJobs/SchedulerJobs.Services/ELinksService.cs, SchedulerJobs/SchedulerJobs.Services/HttpClients/ELinksApiClient.cs, SchedulerJobs/SchedulerJobs.Services/HttpClients/IELinksApiClient.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryPersonRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Functions/GetJudiciaryUsersFunctionTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/ELinksServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/Functions/GetJudiciaryUsersFunction.cs, SchedulerJobs/SchedulerJobs/Startup.cs, SchedulerJobs/SchedulerJobs/packages.lock.json, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7407
=> VIH-7407 Add eLinks api function for bulk insert

azure-pipelines.release.yml
Please remove this line and everything above and fill the following sections:
VIH-7407
```
[ ] Yes
[X] No
```
=> VIH-7407 Added_variables_for_elinks

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/Models/JudiciaryPersonModel.cs, SchedulerJobs/SchedulerJobs.Services/ELinksService.cs, SchedulerJobs/SchedulerJobs.Services/HttpClients/ELinksApiClient.cs, SchedulerJobs/SchedulerJobs.Services/HttpClients/IELinksApiClient.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryPersonRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Functions/AzureFunctionTestBaseSetup.cs, SchedulerJobs/SchedulerJobs.UnitTests/Functions/GetJudiciaryUsersFunctionTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/ELinksServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/Functions/GetJudiciaryUsersFunction.cs, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/packages.lock.json, azure-pipelines.release.yml
https://tools.hmcts.net/jira/browse/VIH-7407
=> VIH-7407 Adding property HasLeft update BAPI nuget

SchedulerJobs/SchedulerJobs.Services/ELinksService.cs, SchedulerJobs/SchedulerJobs.Services/ELinksServiceStub.cs, SchedulerJobs/SchedulerJobs.Services/Extensions/StringExtensions.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/ELinksServiceStubTests.cs, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/Startup.cs, SchedulerJobs/SchedulerJobs/appsettings.Development.json, SchedulerJobs/SchedulerJobs/appsettings.json, azure-pipelines.release.yml, azure-pipelines.yml
VIH-7626
Introduce an ELinks stub to provide a static set of automation and manual users, managed by a config
```
[ ] Yes
[x] No
```
=> VIH-7626 Add ELinks Stub

azure-pipelines.release.yml
VIH-7626
* update variable assignment for elink service stub
```
[ ] Yes
[x] No
```
=> VIH-7626 Update CD pipleline

SchedulerJobs/SchedulerJobs.UnitTests/Functions/GetJudiciaryUsersFunctionTests.cs, SchedulerJobs/SchedulerJobs/Functions/GetJudiciaryUsersFunction.cs
https://tools.hmcts.net/jira/browse/VIH-7703
https://tools.hmcts.net/jira/browse/VIH-7692
- Removed GetJudiciaryUsersFunction functionality 
- Updated unit tests
```
[ ] Yes
[x] No
```
=> VIH-7703 Hide eJud from prod release 1.26

azure-pipelines.release.yml, azure-pipelines.yml
VIH-7660
Replaced shaed's PAT with that of the HMCTS account
```
[ ] Yes
[X] No
```
=> VIH-7660 replace Shaed PAT with HMCTS PAT

SchedulerJobs/SchedulerJobs.UnitTests/Functions/GetJudiciaryUsersFunctionTests.cs, SchedulerJobs/SchedulerJobs/Functions/GetJudiciaryUsersFunction.cs
VIH-7407
VIH-7703
Readding calls to eLinks Service for importing judiciary people and leavers
Readded tests
```
[ ] Yes
[x] No
```
=> VIH-7407 Readding eJud eLinks for data integration

SchedulerJobs/SchedulerJobs.Services/ELinksService.cs, azure-pipelines.release.yml, azure-pipelines.yml
* Remove the unnecessary Task.Delay method - Scheduler Job (eLinks Data import)
* Configure ELinksApiGetPeopleUpdatedSinceDays from a secret to a Config value
https://tools.hmcts.net/jira/browse/VIH-7938
```
[ ] Yes
[X] No
```
=> VIH-7938 Refactor and reconfigure 

azure-pipelines.release.yml
https://tools.hmcts.net/jira/browse/VIH-7938
- VIH-7938 UuseElinksStub to false for prod and preprod
```
[ ] Yes
[X] No
```
=> VIH-7938 UseElinksStub to false for prod and preprod

azure-pipelines.release.yml
https://tools.hmcts.net/jira/browse/VIH-7938
- "VIH-7938 UseELinksStub to false in Preprod also
```
[ ] Yes
[X] No
```
=> VIH-7938 UseELinksStub to false in Preprod also

SchedulerJobs/SchedulerJobs.AcceptanceTests/SchedulerJobs.AcceptanceTests.csproj, SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/Constants/AzureAdUserRoles.cs, SchedulerJobs/SchedulerJobs.Services/AnonymiseHearingsConferencesDataService.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Services/AnonymiseHearingsConferencesDataServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/Functions/AnonymiseHearingsConferencesAndDeleteAadUsersFunction.cs, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8632
=> VIH-8632 VHOs are no longer deleted from AD

SchedulerJobs/SchedulerJobs.Services/Interfaces/IReconcileHearingAudioService.cs, SchedulerJobs/SchedulerJobs.Services/ReconcileHearingAudioService.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Functions/ReconcileHearingAudioWithStorageFunctionTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/ReconcileHearingAudioServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/Functions/ReconcileHearingAudioWithStorageFunction.cs, SchedulerJobs/SchedulerJobs/Startup.cs, SchedulerJobs/SchedulerJobs/packages.lock.json
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/VIH-8547
New Scheduler job for Reconciliation of Audio files with Wowza storage with conferences on the day.
```
[ ] Yes
[x ] No
```
=> VIH-8547 New Reconcile Scheduler job

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/AnonymiseHearingsConferencesDataService.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Services/AnonymiseHearingsConferencesDataServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/packages.lock.json, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-8728
- Ensuring user admin account is not deleted when scheduler job runs
- Updated User.Client package to v1.29.1
- Removed redundant using references
```
[ ] Yes
[ x] No
```
=> VIH-8728 - Ensuring user admin account is not deleted when scheduler job runs

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8547
```
[ ] Yes
[ x] No
```
=> VIH-8547 Reference changes of Video Api client

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/ApiHelper/NotificationServiceTokenHandler.cs, SchedulerJobs/SchedulerJobs.Common/Configuration/FeatureToggles.cs, SchedulerJobs/SchedulerJobs.Common/Configuration/ServicesConfiguration.cs, SchedulerJobs/SchedulerJobs.Common/Enums/RoleNames.cs, SchedulerJobs/SchedulerJobs.Common/Enums/UserRoleNames.cs, SchedulerJobs/SchedulerJobs.Common/Extensions/DateExtensions.cs, SchedulerJobs/SchedulerJobs.Common/SchedulerJobs.Common.csproj, SchedulerJobs/SchedulerJobs.Common/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/HearingNotificationService.cs, SchedulerJobs/SchedulerJobs.Services/Interfaces/IHearingNotificationService.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/AddNotificationRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Common/ApiHelper/NotificationServiceTokenHandlerTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Functions/SendHearingNotificationsFunctionTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/HearingNotificationServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/Configuration/FeatureToggles.cs, SchedulerJobs/SchedulerJobs/Functions/SendHearingNotificationsFunction.cs, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/Startup.cs, SchedulerJobs/SchedulerJobs/packages.lock.json, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7318
https://tools.hmcts.net/jira/browse/VIH-8898
```
[ ] Yes
[x ] No
```
=> VIH-8898 add new scheduler job for hearing reminder in next 48 hrs

SchedulerJobs/SchedulerJobs.Services/ELinksServiceStub.cs
https://tools.hmcts.net/jira/browse/VIH-9078
- hardcoding leavers id for stubbed version of elink service to avoid adding multiple records
```
[ ] Yes
[x] No
```
=> VIH-9078 hardcoding stubbed data

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/Models/JudiciaryPersonModel.cs, SchedulerJobs/SchedulerJobs.Services/ELinksService.cs, SchedulerJobs/SchedulerJobs.Services/ELinksServiceStub.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryPersonRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Services/ELinksServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9109
Sometimes the deserialisation of the eLinks People API response fails, this is because the Id is a uuid and we are casting it to a Guid.
Instead, store it as string.
```
[ ] Yes
[x] No
```
=> VIH-9109 Change JudiciaryPerson id from Guid to string

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/ELinksService.cs, SchedulerJobs/SchedulerJobs.Services/ELinksServiceStub.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryPersonStagingRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Services/ELinksServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9104
- updated function to consume new endpoints and add records to JudiciaryPersonStaging table
```
[ ] Yes
[x] No
```
=> VIH-9104 Save raw ejud data

SchedulerJobs/SchedulerJobs.Services/AnonymiseHearingsConferencesDataService.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/AnonymiseHearingsConferencesDataServiceTests.cs
https://tools.hmcts.net/jira/browse/VIH-9172
If there is an exception retrieving a user from Azure AD, catch it and continue to prevent the function from crashing
```
[ ] Yes
[x] No
```
=> VIH-9172 Anonymisation function - catch error retrieving user from Azure AD

SchedulerJobs/SchedulerJobs.Services/ELinksService.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/ELinksServiceTests.cs
https://tools.hmcts.net/jira/browse/VIH-9142
Re-instate the original json deserializer so that the "more_pages" API property is deserialized
```
[ ] Yes
[x] No
```
=> VIH-9142 Fix for eLinks job not looping over all pages

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/AnonymiseHearingsConferencesDataService.cs, SchedulerJobs/SchedulerJobs.Services/ELinksService.cs, SchedulerJobs/SchedulerJobs.Services/JobHistoryService.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Functions/GetJudiciaryUsersFunctionTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Functions/RunAnonymiseHearingsConferencesAndDeleteAadUsersFunctionTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/AnonymiseHearingsConferencesDataServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/Services/JobHistoryServiceTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/Functions/AnonymiseHearingsConferencesAndDeleteAadUsersFunction.cs, SchedulerJobs/SchedulerJobs/Functions/GetJudiciaryUsersFunction.cs, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9070
Implemented call to UpdateJobHistory endpoint success/failure
```
[ ] Yes
[X ] No
```
=> VIH-9070 Using new JobHistory endpoint in anonymise job

charts/vh-scheduler-jobs/Chart.yaml, charts/vh-scheduler-jobs/values.yaml
VIH-9236
Add missing config
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add missing config

azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
VIH-9236
Correct Code Coverage with SonarCloud
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Correct Code Coverage with SonarCloud

SchedulerJobs/SchedulerJobs.AcceptanceTests/Configuration/Setup.cs, SchedulerJobs/SchedulerJobs.AcceptanceTests/SchedulerJobs.AcceptanceTests.csproj, SchedulerJobs/SchedulerJobs.AcceptanceTests/Tests/Health.cs, SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/SchedulerJobs.Common.csproj, SchedulerJobs/SchedulerJobs.Common/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/SchedulerJobs.UnitTests.csproj, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/appsettings.json, SchedulerJobs/SchedulerJobs/packages.lock.json, SchedulerJobs/Testing.Common/Testing.Common.csproj, azure-pipelines.release.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.yml, charts/vh-scheduler-jobs/Chart.yaml, charts/vh-scheduler-jobs/values.yaml
https://tools.hmcts.net/jira/browse/VIH-9198
Upgrade application from .NET core 3.1 to .NET 6
```
[ ] Yes
[X] No
```
=> VIH-9198 Upgrade to dotnet 6

README.md, variables/shared.yaml
https://tools.hmcts.net/jira/browse/VIH-9330
- Fixes an error with the sds-release pipeline looking for the wrong docker image
- Add documentation for SchedulerJobs.Sds
```
[ ] Yes
[x] No
```
=> VIH-9330 Fix error in SDS release pipeline and update readme

charts/vh-scheduler-jobs/templates/CronJob.yaml, charts/vh-scheduler-jobs/templates/_metadata.tpl
VIH-9351 - amend helm templates
VIH-9351 - amend helm templates
```
[ ] Yes
[ x ] No
```
=> VIH-9351 - amend helm templates

README.md, charts/vh-scheduler-jobs/Chart.yaml, charts/vh-scheduler-jobs/values.yaml, variables/shared.yaml
https://tools.hmcts.net/jira/browse/VIH-9330
```
[ ] Yes
[x] No
```
=> VIH-9330 Remove redundant settings for SDS

SchedulerJobs/SchedulerJobs.Sds.UnitTests/Jobs/HearingsAllocationJobTests.cs, SchedulerJobs/SchedulerJobs.Sds/Jobs/HearingsAllocationJob.cs, SchedulerJobs/SchedulerJobs.Sds/Program.cs, SchedulerJobs/SchedulerJobs.UnitTests/Functions/HearingsAllocationFunctionTests.cs, SchedulerJobs/SchedulerJobs/Functions/HearingsAllocationFunction.cs
https://tools.hmcts.net/jira/browse/VIH-9393
=> VIH-9393 - added new scheduler job hearing allocation

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/Configuration/FeatureToggles.cs, SchedulerJobs/SchedulerJobs.Sds.UnitTests/Jobs/HearingsAllocationJobTests.cs, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds/Jobs/HearingsAllocationJob.cs, SchedulerJobs/SchedulerJobs.Sds/Program.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/HearingAllocationServiceTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/HearingAllocationService.cs, SchedulerJobs/SchedulerJobs.Services/Interfaces/IHearingNotificationService.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/Functions/HearingsAllocationFunctionTests.cs, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/Functions/HearingsAllocationFunction.cs, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/Startup.cs, SchedulerJobs/SchedulerJobs/packages.lock.json, charts/vh-scheduler-jobs/Chart.yaml, charts/vh-scheduler-jobs/values.dev.template.yaml, charts/vh-scheduler-jobs/values.yaml
https://tools.hmcts.net/jira/browse/VIH-9397
- Update the Hearings Allocations job to retrieve unallocated hearings and allocate them when the work allocation feature is toggled on
- Add missing yaml changes for the SDS job
```
[ ] Yes
[x] No
```
=> VIH-9397 Allocate available VHO to hearing

charts/vh-scheduler-jobs/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-9397
Updates the cron job reference in the dev template
```
[ ] Yes
[x] No
```
=> VIH-9397 Update cron job name in yaml file

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
VIH-9517 - Add master release pipeline
VIH-9517 - Add master release pipeline
```
[ ] Yes
[x ] No
```
=> VIH-9517 - Add master release pipeline

azure-pipelines.sds.pr-release.yml
VIH-9532 - Amend PR Pipeline
VIH-9532 - Amend PR Pipeline
```
[ ] Yes
[ x ] No
```
=> VIH-9532 - Amend PR Pipeline

charts/vh-scheduler-jobs/Chart.yaml, charts/vh-scheduler-jobs/values.yaml
https://tools.hmcts.net/jira/browse/VIH-9361
```
[ ] Yes
[x] No
```
=> VIH-9361 Move app urls from secrets to environment variables

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/ApiHelper/ApiRequestHelper.cs, SchedulerJobs/SchedulerJobs.Common/Models/JudiciaryLeaverModel.cs, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services.UnitTests/ELinksServiceTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/ELinksService.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryLeaverRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryPersonRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/packages.lock.json, charts/vh-scheduler-jobs/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-9361
- Changes the unique identifier for judiciary persons from id to personal code
- Updates tests to mock the API client response in snake case, to match the real API
- Fixes code smells
```
[ ] Yes
[x] No
```
=> VIH-9361 Change eLinks unique identifier from Id to Personal Code

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/SchedulerJobs.csproj, SchedulerJobs/SchedulerJobs/packages.lock.json
VIH-9679
Update api clients to receive deserialised error messages
```
[ ] Yes
[x] No
```
=> VIH-9679 Update api clients to receive deserialised error messages

CODEOWNERS
https://tools.hmcts.net/jira/browse/VIH-9753
Add vh-qa team as codeowners
```
[ ] Yes
[x] No
```
=> VIH-9753 Update CODEOWNERS

azure-pipelines.sds.release.yml, variables/shared.yaml, variables/staging.yaml
VIH-9814 - Amend Release Pipeline
```
[ ] Yes
[ x ] No
```
=> VIH-9814 - Amend Release Pipeline

azure-pipelines.sds.pr-release.yml
PR workaround
```
[ ] Yes
[X] No
```
=> VIH-0000 PR workaround

CODEOWNERS
https://tools.hmcts.net/jira/browse/VIH-10016
Update so all code changes need vh and vh-qa & so that devops approve the pipeline files and the .github folder
```
[ ] Yes
[x] No
```
=> VIH-10016 update codeowner

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/Configuration/FeatureToggles.cs, SchedulerJobs/SchedulerJobs.Common/SchedulerJobs.Common.csproj, SchedulerJobs/SchedulerJobs.Common/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds/Jobs/BaseJob.cs, SchedulerJobs/SchedulerJobs.Sds/Program.cs, SchedulerJobs/SchedulerJobs.Sds/Properties/launchSettings.json, SchedulerJobs/SchedulerJobs.Services.UnitTests/HearingNotificationServiceTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/HearingNotificationService.cs, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/SchedulerJobs.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs/Startup.cs, SchedulerJobs/SchedulerJobs/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-10062
- Update Launch Darkly client so that feature toggles can be set per environment (use same implementation as bookings api)
- Change jobs to only use redis lock concurrency mechanism when running remotely
- Fix code smells
- Remove book and confirm toggle (now always switched on)
```
[ ] Yes
[x] No
```
=> VIH-10062 Update LD client to include the environment name

azure-pipelines.sds.pr-release.yml
removing pr workaround
```
[ ] Yes
[X] No
```
=> VIH-0000 removing pr workaround

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/Models/JudiciaryPersonModel.cs, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/Mappers/AddNotificationRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryPersonRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryPersonStagingRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json
VIH-10086
track and map the work phone for an ejud person
=> VIH-10086 track and map the work phone for an ejud person

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services.UnitTests/HearingNotificationServiceProcessMultiDaysTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/HearingNotificationServiceTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/HearingNotificationService.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/Testing.Common/Testing.Common.csproj, charts/vh-scheduler-jobs/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10235
- Process subsequent days of multi day hearing
- `TelephoneParticipants` property has been removed from the ParticipantResponse - update the tests
=> VIH-10235 Send reminder emails to individuals on subsequent days of multi day hearing

SchedulerJobs/Directory.Packages.props, SchedulerJobs/SchedulerJobs.AcceptanceTests/SchedulerJobs.AcceptanceTests.csproj, SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/SchedulerJobs.Common.csproj, SchedulerJobs/SchedulerJobs.Common/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds.UnitTests/SchedulerJobs.Sds.UnitTests.csproj, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds/Dockerfile, SchedulerJobs/SchedulerJobs.Sds/SchedulerJobs.Sds.csproj, SchedulerJobs/SchedulerJobs.Services.UnitTests/SchedulerJobs.Services.UnitTests.csproj, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/Testing.Common/Testing.Common.csproj, SchedulerJobs/global.json, azure-pipelines.sds.pr-release.yml
https://tools.hmcts.net/jira/browse/VIH-10125
=> VIH-10125 Upgrade to .NET 8

SchedulerJobs/Directory.Packages.props
https://tools.hmcts.net/jira/browse/VIH-10125
=> VIH-10125 Disable central package management

SchedulerJobs/SchedulerJobs.Common/ApiHelper/ELinksApiDelegatingHandler.cs
VIH-10657
Update ELinks client handler header to Token
=> VIH-10657 Update ELinks client handler header to Token

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/Models/JudiciaryPersonModel.cs, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services.UnitTests/Mappers/JudiciaryPersonRequestMapperTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/Mappers/JudiciaryPersonStagingRequestMapperTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryPersonRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/Mappers/JudiciaryPersonStagingRequestMapper.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, charts/vh-scheduler-jobs/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10790
- Add `Deleted` property to the eLinks judiciary person model, so that it is captured from the eLinks API response when deserialised
- Pass `Deleted` property to Bookings API
- Add mapper tests
=> VIH-10790 Handle deleted eLinks users

azure-pipelines.sds.master-release.yml
https://tools.hmcts.net/jira/browse/VIH-11075
Run the sonar checks as part of the master release pipeline in order to get code coverage results against the main branch. As done with the other apps
=> VIH-11075 Add sonar checks to master release pipeline

azure-pipelines.sds.master-release.yml, variables/demo.yaml
See VIH-11181](https://tools.hmcts.net/jira/browse/VIH-11181)
enable demo image and helm buildpush
=> VIH-11181 enable demo image build push

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Common/SchedulerJobs.Common.csproj, SchedulerJobs/SchedulerJobs.Common/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services.UnitTests/HearingAllocationServiceTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/HearingNotificationServiceProcessMultiDaysTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/HearingNotificationServiceTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/HearingAllocationService.cs, SchedulerJobs/SchedulerJobs.Services/HearingNotificationService.cs, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json, SchedulerJobs/Testing.Common/Testing.Common.csproj
=> VIH-10899 upgrade packages

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services.UnitTests/HearingNotificationServiceProcessMultiDaysTests.cs, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/Testing.Common/Testing.Common.csproj
Jira link
[VIH-11091](https://tools.hmcts.net/jira/browse/VIH-11091)
Change description
removed Faker.NetCore
=> VIH-11091 - replace Faker.NetCore with Bogus

.github/workflows/launch-darkly-find-code-refs-in-pr.yml, .github/workflows/launch-darkly-flag-sync.yml, .github/workflows/osv-scanner-pr.yml
VIH-11246
Update to the GitHub Actions:
* Switch the full LD code scan to run against master only and on a schedule
* Add the LD code scan on diff to run against PRs only
* Turn off fail on vuln for OSV scanner
=> VIH-11246 update GH Actions

.github/renovate.json
VIH-11252
add renovate job for Helm Chart Release function
=> VIH-11252 Create renovate.json

charts/vh-scheduler-jobs/Chart.yaml, charts/vh-scheduler-jobs/values.dev.template.yaml, charts/vh-scheduler-jobs/values.yaml
https://tools.hmcts.net/jira/browse/VIH-11277
Currently Cron doesn't run in lower environments, as vm's are off. So need to change cron to suit VM time.
- [x ] commit messages are meaningful and follow good commit message guidelines
=> VIH-11277 Change cron run time

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-release.yml, sds-git-version-config.yml
VIH-11126
Coverage report path is incorrect, due to no code changes in the previous change it was missed
=> VIH-11126 update coverage report to match compose output

SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds/Program.cs, SchedulerJobs/SchedulerJobs.Sds/SchedulerJobs.Sds.csproj
https://tools.hmcts.net/jira/browse/VIH-11334
=> VIH-11334 Migrate to OpenTelemetry

charts/vh-scheduler-jobs/Chart.yaml, charts/vh-scheduler-jobs/templates/_jobspec.tpl, charts/vh-scheduler-jobs/templates/secretproviderclass.yaml, charts/vh-scheduler-jobs/values.dev.template.yaml, charts/vh-scheduler-jobs/values.yaml
https://tools.hmcts.net/jira/browse/VIH-11346
Undo changes for scheduler jobs
=> VIH-11346 revert helm changes

azure-pipelines.sds.pr-release.yml
Remove reference to non-existent variable group
=> VIH-0000 Pipeline fix

.github/workflows/close-pr.yaml
VIH-11409 
Update close-pr action to use correct branch var
=> VIH-11409 Update close-pr action to use correct branch var

SchedulerJobs/SchedulerJobs.AcceptanceTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Sds.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services.UnitTests/packages.lock.json, SchedulerJobs/SchedulerJobs.Services/SchedulerJobs.Services.csproj, SchedulerJobs/SchedulerJobs.Services/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-11424
Update reference to BookingsApi.Client
=> VIH-11424 Replace BookingsApi.Common.DotNet6 project
